data:
  # image: tianon/true:latest (docker/fig#919)
  image: busybox:latest
  volumes:
    - /data
    - /var/lib/postgresql/data
  entrypoint: /bin/echo

redis:
  image: redis:2.8
  volumes_from:
    - data

postgres:
  image: postgres:9.4
  volumes_from:
    - data

www:
  build: .
  ports:
    - "8080"
  links:
    - postgres
    - redis
  volumes_from:
    - data
  entrypoint: sentry
  command: start --noinput
  environment:
    - SECRET_KEY
    - SERVER_EMAIL
    - SENTRY_URL_PREFIX

